In [5]:
import pandas as pd
from sqlalchemy import create_engine

In [48]:
# Create the connection string
connection_string = 'postgresql://postgres:postgres@localhost:5432/pokemon'

# Create the SQLAlchemy engine
engine = create_engine(connection_string)

In [19]:
csv_data.rename(columns={'classfication': 'classification'}, inplace=True)
csv_data.columns

Index(['abilities', 'against_bug', 'against_dark', 'against_dragon',
       'against_electric', 'against_fairy', 'against_fight', 'against_fire',
       'against_flying', 'against_ghost', 'against_grass', 'against_ground',
       'against_ice', 'against_normal', 'against_poison', 'against_psychic',
       'against_rock', 'against_steel', 'against_water', 'attack',
       'base_egg_steps', 'base_happiness', 'base_total', 'capture_rate',
       'classification', 'defense', 'experience_growth', 'height_m', 'hp',
       'japanese_name', 'name', 'percentage_male', 'pokedex_number',
       'sp_attack', 'sp_defense', 'speed', 'type1', 'type2', 'weight_kg',
       'generation', 'is_legendary'],
      dtype='object')

In [21]:
basic_details_columns = ['pokedex_number', 'name', 'japanese_name', 'type1', 'type2', 'classification', 'generation', 'is_legendary']
basic_details = csv_data[basic_details_columns]
basic_details

,pokedex_number,name,japanese_name,type1,type2,classification,generation,is_legendary
0,1,Bulbasaur,Fushigidaneフシギダネ,grass,poison,Seed Pokémon,1,0
1,2,Ivysaur,Fushigisouフシギソウ,grass,poison,Seed Pokémon,1,0
2,3,Venusaur,Fushigibanaフシギバナ,grass,poison,Seed Pokémon,1,0
3,4,Charmander,Hitokageヒトカゲ,fire,NaN,Lizard Pokémon,1,0
4,5,Charmeleon,Lizardoリザード,fire,NaN,Flame Pokémon,1,0
...,...,...,...,...,...,...,...,...
796,797,Celesteela,Tekkaguyaテッカグヤ,steel,flying,Launch Pokémon,7,1
797,798,Kartana,Kamiturugiカミツルギ,grass,steel,Drawn Sword Pokémon,7,1
798,799,Guzzlord,Akuzikingアクジキング,dark,dragon,Junkivore Pokémon,7,1
799,800,Necrozma,Necrozmaネクロズマ,psychic,NaN,Prism Pokémon,7,1
800,801,Magearna,Magearnaマギアナ,steel,fairy,Artificial Pokémon,7,1

In [36]:
against_other_type_columns = [ 'against_bug',
 'against_dark',
 'against_dragon',
 'against_electric',
 'against_fairy',
 'against_fight',
 'against_fire',
 'against_flying',
 'against_ghost',
 'against_grass',
 'against_ground',
 'against_ice',
 'against_normal',
 'against_poison',
 'against_psychic',
 'against_rock',
 'against_steel',
 'against_water'
 ]

stats_columns = list(set(csv_data.columns) - (set(basic_details_columns).union(set(against_other_type_columns))))

In [44]:
basic_details = csv_data[basic_details_columns]
stats = csv_data[stats_columns]
against_other_type = csv_data[against_other_type_columns]

801